app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// routing for api
Route::group(['prefix' => 'api/v1'], function () {
    Route::resource('/users', '\App\Http\Controllers\UsersApi');
});

Route::resource('/user', '\App\Http\Controllers\Users');

Route::get('/', '\App\Http\Controllers\Users@index');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Users.php
<?php

namespace App\Http\Controllers;

use App\Http\Models\Privileges;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Models\User;
use Illuminate\Support\Facades\Validator;

class Users extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('list-users', ['users' => User::all()]  );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('create-user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $form = \Input::all();

        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'first-name' => 'required',
            'last-name' => 'required',
            'password' => 'required|confirmed'
        ]);

        if ($validator->fails()) {
            return redirect('user/create')
                ->withErrors($validator)
                ->withInput();
        }

        $user = new User();
        $user->email = $form['email'];
        $user->first_name = $form['first-name'];
        $user->last_name = $form['last-name'];
        $user->password = $form['password'];
        $user->save();

        if (isset($form['pv']) && is_array($form['pv'])) {
            $privileges = Privileges::all();
            foreach ($privileges as $p) {
                if (false !== array_search($p->name, $form['pv'])) {
                    $pivot = [$p->id => ['created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s")]];
                    $user->privileges()->attach($pivot);
                }
            }
        }

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        if (! $user)
        {
            return redirect('/');
        }

        $pvs = [];
        foreach ($user->privileges as $p)
        {
            $pvs[] = $p->name;
        }

        return view('edit-user', ['user' => $user, 'pvs' => $pvs]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $form = \Input::all();

        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'first-name' => 'required',
            'last-name' => 'required',
            'password' => 'confirmed'
        ]);

        if ($validator->fails()) {
            return redirect("user/{$id}/edit")
                ->withErrors($validator)
                ->withInput();
        }

        $user = User::find($id);

        if (! $user)
        {
            return redirect("user/{$id}/edit")
                ->with('id', $id)
                ->withInput();
        }

        $user->email = $form['email'];
        $user->first_name = $form['first-name'];
        $user->last_name = $form['last-name'];

        if (!empty($form['password'])) {
            $user->password = $form['password'];
        }
        $user->save();

        $pvs = [];
        if (isset($form['pv']) && is_array($form['pv'])) {
            $privileges = Privileges::all();
            foreach ($privileges as $p) {
                if (false !== array_search($p->name, $form['pv'])) {
                    $pvs[] = $p->id;
                }
            }
        }
        $user->privileges()->sync($pvs);

        return redirect('/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        if (! $user)
        {
            return redirect('/');
        }

        // remove related privileges
        $user->privileges()->sync([]);

        // remove user
        $user->delete();

        return [ 'id' => $id ];
    }
}

app/Http/Controllers/UsersApi.php
<?php

namespace App\Http\Controllers;

use App\Http\Api\Api;
use App\Http\Models\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class UsersApi extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return Api::getAllUsers();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return Api::errorMessage();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        return Api::errorMessage();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        return Api::errorMessage();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return Api::errorMessage();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        return Api::errorMessage();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        return Api::errorMessage();
    }
}

resources/views/create-user.blade.php
@extends('template')

@section('content')

    <h1>Add new user</h1>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <p>
        All fields are required.
    </p>

    <form id="add-user-form" method="post" action="{{ route('user.store') }}">
        {!! csrf_field() !!}
        <table border="1">
            <tbody>
                <tr>
                    <td>First Name:</td>
                    <td><input type="text" name="first-name" value="{{ old('first-name') }}"/></td>
                </tr>
                <tr>
                    <td>Last Name:</td>
                    <td><input type="text" name="last-name" value="{{ old('last-name') }}"/></td>
                </tr>
                <tr>
                    <td>Email address:</td>
                    <td><input type="text" name="email" value="{{ old('email') }}" /></td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td><input type="password" name="password" /></td>
                </tr>
                <tr>
                    <td>Please repeat the password:</td>
                    <td><input type="password" name="password_confirmation" /></td>
                </tr>
            </tbody>
        </table>

        <br />
        <p>
            Privileges
        </p>
        <table border="1">
            <tbody>
                <tr>
                    <td>Resource A</td>
                    <td>
                        <label>
                            <input type="checkbox" value="Read from A" name="pv[]" />Read
                        </label>
                        <label>
                            <input type="checkbox" value="Write to A" name="pv[]" />Write
                        </label>
                    </td>
                </tr>
                <tr>
                    <td>Resource B</td>
                    <td>
                        <label>
                            <input type="checkbox" value="Read from B" name="pv[]" />Read
                        </label>
                        <label>
                            <input type="checkbox" value="Write to B" name="pv[]" />Write
                        </label>
                    </td>
                </tr>
                <tr>
                    <td>Resource C</td>
                    <td>
                        <label>
                            <input type="checkbox" value="Read from C" name="pv[]" />Read
                        </label>
                        <label>
                            <input type="checkbox" value="Write to C" name="pv[]"  />Write
                        </label>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>

    <div style="margin-top: 10px;">
        <button class="store-user">Add</button>
    </div>

@endsection

resources/views/edit-user.blade.php
@extends('template')

@section('content')

    <h1>Edit</h1>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form id="edit-user-form" method="post" action="{{ route('user.update', $user->id) }}">
        {!! csrf_field() !!}
        <input type="hidden" name="_method" value="PUT" />
        <table border="1">
            <tbody>
                <tr>
                    <td>First Name:</td>
                    <td><input type="text" name="first-name" value="{{ $user->first_name }}" /></td>
                </tr>
                <tr>
                    <td>Last Name:</td>
                    <td><input type="text" name="last-name" value="{{ $user->last_name }}" /></td>
                </tr>
                <tr>
                    <td>Email address:</td>
                    <td><input type="text" name="email" value="{{ $user->email }}" /></td>
                </tr>
                <tr>
                    <td>Change password of leave empty:</td>
                    <td><input type="password" name="password" /></td>
                </tr>
                <tr>
                    <td>Please repeat the password:</td>
                    <td><input type="password" name="password_confirmation" /></td>
                </tr>
            </tbody>
        </table>

        <br />
        <p>
            Privileges
        </p>
        <table border="1">
            <tbody>
            <tr>
                <td>Resource A</td>
                <td>
                    <label>
                        <input type="checkbox" value="Read from A" name="pv[]" @if (false !== array_search('Read from A', $pvs))checked="checked"@endif />Read
                    </label>
                    <label>
                        <input type="checkbox" value="Write to A" name="pv[]" @if (false !== array_search('Write to A', $pvs))checked="checked"@endif />Write
                    </label>
                </td>
            </tr>
            <tr>
                <td>Resource B</td>
                <td>
                    <label>
                        <input type="checkbox" value="Read from B" name="pv[]" @if (false !== array_search('Read from B', $pvs))checked="checked"@endif />Read
                    </label>
                    <label>
                        <input type="checkbox" value="Write to B" name="pv[]" @if (false !== array_search('Write to B', $pvs))checked="checked"@endif />Write
                    </label>
                </td>
            </tr>
            <tr>
                <td>Resource C</td>
                <td>
                    <label>
                        <input type="checkbox" value="Read from C" name="pv[]" @if (false !== array_search('Read from C', $pvs))checked="checked"@endif />Read
                    </label>
                    <label>
                        <input type="checkbox" value="Write to C" name="pv[]"  @if (false !== array_search('Write to C', $pvs))checked="checked"@endif />Write
                    </label>
                </td>
            </tr>
            </tbody>
        </table>
    </form>

    <div style="margin-top: 10px;">
        <button class="update-user">Update</button>
    </div>

resources/views/list-users.blade.php
@extends('template')

@section('content')
    <div>
        <button class="add-user" data-url="{{ route('user.create') }}}">Add new user</button>
    </div>

    <form id="delete-user-form" method="post">
        {!! csrf_field() !!}
        <input type="hidden" id="delete-user-id" name="id" value="" />
        <input type="hidden" name="_method" value="DELETE" />
    </form>

    <div style="margin-top: 10px;">

        <table border="1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email address</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $key => $user)
                    <tr id="user-{{ $user->id }}">
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $user->first_name }}</td>
                        <td>{{ $user->last_name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>
                            <button class="edit-user" data-url="{{ route('user.edit', $user->id) }}">Edit</button>
                            <button class="delete-user" data-id="{{ $user->id }}" data-url="{{ route('user.destroy', $user->id) }}">Delete</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="_token" content="{!! csrf_token() !!}" />
    <title>Test Task</title>

    <meta http-equiv="Expires" content="0" />
    <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate" />
    <meta http-equiv="Cache-Control" content="post-check=0, pre-check=0" />
    <meta http-equiv="Pragma" content="no-cache" />

    {{--<link href="/css/app.css" rel="stylesheet">--}}
</head>
<body>
    @yield('content')
    <script src="{{ url('/js/jquery-2.1.1.min.js') }}"></script>
    <script src="{{ url('/js/jquery.form.js') }}"></script>
    <script src="{{ url('/js/application.js') }}"></script>
    <script>
        $(document).ready(function(){

            app.init();

        });
    </script>
</body>
</html>